### ISSUE TITLE
demo.py can't initialize dlc

### ISSUE THREAD

**Issue by BanjoIsland** [ctxis/Furby#4]
Hi!
I've been trying to run demo.py but have been getting this error:

Traceback (most recent call last):
  File "demo.py", line 197, in <module>
    make_hacked_inverting()
  File "demo.py", line 41, in make_hacked_inverting
    D = dlc(dlc_in)
  File "C:\Furby-master\furby.py", line 1371, in __init__
    d = section_generators[sec](rawbytes)
  File "C:\Furby-master\furby.py", line 52, in __init__
    self.__initialise__()
  File "C:\\Furby-master\furby.py", line 1238, in __initialise__
    this_sequence.append(self.__unpack__(2))
  File "C:\Furby-master\furby.py", line 102, in __unpack__
    return struct.unpack("<H", bla)[0]
struct.error: unpack requires a string argument of length 2

I'm running python 2.7.12 on a windows 10 machine. The path to the dlc is correct, and I'm using the dlc from this repo.  Any ideas?

**Comment by BanjoIsland** [comment]
Figured it out. In Windows, you have to change the f.read parsing commands in furby.py to be "rb" instead of just "r".
