### ISSUE TITLE
Multiple Errors When Running Demo.py

### ISSUE THREAD

**Issue by SaSoGaming** [ctxis/Furby#5]
I'm having multiple errors when trying to run demo.py which I believe has been suited to replace the audio in the DLC file to have custom music.

Here are the errors I'm getting:

Traceback (most recent call last):
  File "C:\Users\*\Downloads\Furby-master\Furby-master\demo.py", line 53, in <module>
    make_hacked_inverting()
  File "C:\Users\*\Downloads\Furby-master\Furby-master\demo.py", line 41, in make_hacked_inverting
    D = dlc("./dlc/dlc2/tu003410.dlc")
  File "C:\Users\*\Downloads\Furby-master\Furby-master\furby.py", line 1341, in __init__
    self.dlc_header = self.HEADER_section(f.read(0x288))
  File "C:\Users\*\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1200: character maps to <undefined>

Is there anyway to solve this errors? I don't really know Python so any help on these errors would be greatly appreciated. Thank you.

*(name cut for privacy)

**Comment by meilleur102** [comment]
did you fix this? I have the same issue. Thanks

**Comment by SnackersLC** [comment]
The code runs out of the box in Ubuntu with Python 2.7.14 - 2.7.18. Windows has some issues with furby.py.

**Comment by BNNorman** [comment]
I'm using windows 11 , python 3.14 and PyCharm - the DLC header is not recognised by Furby.py when I try to use chilli.dlc as a base.

In the class dlc() the header is set as
```
magic_bytes = ("\x00".join("FURBY")) + ("\x00" * 23) + ("\x78\x56\x34\x12\x02\x00\x08\x00")
```
in chillic.dlc the file contains:-

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\WINDOWS\System32\WindowsPowerShell\v1.0> format-hex C:\Users\brian\Documents\PROJECTS\PycharmProjects\FurbyDLC\DLC\chilli.dlc | more


           Path: C:\Users\brian\Documents\PROJECTS\PycharmProjects\FurbyDLC\DLC\chilli.dlc

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   46 00 55 00 52 00 42 00 59 00 00 00 00 00 00 00  F.U.R.B.Y.......
00000010   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00000020   78 56 34 12 02 00 08 00 00 00 00 00 00 00 00 00  xV4.............
00000030   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00000040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 44 00  ..............D.
```
Having placed some code to print out each byte in a few places I get this 
```
magic_bytes
F ,0x0 ,U ,0x0 ,R ,0x0 ,B ,0x0 ,Y ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,x ,V ,4 ,0x12 ,0x2 ,0x0 ,0x8 ,0x0 ,
raw bytes
b ,' ,F ,\ ,x ,0 ,0 ,U ,\ ,x ,0 ,0 ,R ,\ ,x ,0 ,0 ,B ,\ ,x ,0 ,0 ,Y ,\ ,x ,0 ,0 ,\ ,x ,0 ,0 ,\ ,x ,0 ,0 ,\ ,x ,0 ,0 ,\ ,
__read__ magic bytes
b ,' ,F ,\ ,x ,0 ,0 ,U ,\ ,x ,0 ,0 ,R ,\ ,x ,0 ,0 ,B ,\ ,x ,0 ,0 ,Y ,\ ,x ,0 ,0 ,\ ,x ,0 ,0 ,\ ,x ,0 ,0 ,\ ,x ,0 ,0 ,\ ,
```
As you can see the raw bytes differ. Which is probably why Furby.py throws an assert error. But I don't know how to fix it in python. I have tried for several hours today

I have written a simple DLCReadTest.py as follows

```

import os
import string

with open(os.path.normpath("DLC/chilli.dlc"),"rb") as fp:
	contents=fp.read()


print("chilli.dlc")

for p in contents[:40]:
	if chr(p) in string.printable:
		print(chr(p),",",end="")
	else:
		print(hex(p),",",end="")

print("")

print("magicbytes")
magic_bytes = ("\x00".join("FURBY")) + ("\x00" * 23) + ("\x78\x56\x34\x12\x02\x00\x08\x00")
for p in magic_bytes[:40]:
	if p in string.printable:
		print(p,",",end="")
	else:
		print(hex(ord(p)),",",end="")
print("")
```
The output is 
```C:\Users\brian\Documents\PROJECTS\PycharmProjects\FurbyDLC\DLCReadTest.py 
chilli.dlc
F ,0x0 ,U ,0x0 ,R ,0x0 ,B ,0x0 ,Y ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,x ,V ,4 ,0x12 ,0x2 ,0x0 ,0x8 ,0x0 ,
magic bytes
F ,0x0 ,U ,0x0 ,R ,0x0 ,B ,0x0 ,Y ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,0x0 ,x ,V ,4 ,0x12 ,0x2 ,0x0 ,0x8 ,0x0 ,

Process finished with exit code 0

```

So, a binary read from chilli.dlc matches the expected magic_bytes but , as you can see above, the rawbytes returned by __read__ in Furby.py don't match.

I'd like to get my Furby to say/do what I want not just live with the built-in audio etc but this is a stumbling block. My Python skills are sub-optimal on this.

I might try running the code on a Pi instead but I suspect it's the python version that's an issue.

Any help would be gratefully received.
